# Generated by Django 5.2.5 on 2025-11-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("car", "Car"), ("bike", "Bike")], max_length=10
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=8)),
                ("seats", models.IntegerField(default=4)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("Electric", "Electric"),
                        ],
                        default="Petrol",
                        max_length=20,
                    ),
                ),
                ("transmission", models.CharField(blank=True, max_length=20)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
