# Generated by Django 5.2.5 on 2025-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
